name: Build and Deploy App

on:
  #push:
    #branches:
      #- main
  workflow_dispatch:
  
env:
  AWS_REGION: 'us-east-2'  # Cambia según tu región
  REPO_NAME: ${GITHUB_REPOSITORY##*/}  # El nombre del repo será el nombre de tu repo de GitHub
  IMAGE_TAG: ${{ github.sha }}  # El tag de la imagen será el SHA del commit

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the app repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
  
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ env.AWS_REGION }}

      # Crear el repositorio ECR si no existe
      - name: Check if ECR repository exists
        id: ecr_check
        run: |
          aws ecr describe-repositories --repository-names ${{ env.REPO_NAME }} --region ${{ env.AWS_REGION }} || exit 0

      - name: Create ECR repository if not exists
        if: steps.ecr_check.outputs == ''
        run: |
          aws ecr create-repository \
            --repository-name ${{ env.REPO_NAME }} \
            --region ${{ env.AWS_REGION }}
        
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} .

      # Subir la imagen a ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker tag ${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}

      # Guardar la URL de la imagen en las variables de GitHub Actions
      - name: Save image URL for next workflow
        run: echo "IMAGE_URL=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
